name: Currency Alarm (Flutter CI)

on:
  push:
    branches:
      - main

jobs:
  build-android:
    name: Build .apk
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup the Flutter env
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.22.5"

      - uses: Install deps
        run: flutter pub get
      
      #- name: Analyze the Dart code for any errors
      #  run: flutter analyze .

      - name: Run tests
        run: flutter test

      - run: flutter build apk
